# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 00:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityInstance',
            fields=[
                ('id', models.SlugField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('number_of_games', models.PositiveIntegerField(default=1)),
                ('number_of_announcements', models.PositiveIntegerField(default=3)),
                ('length_of_announcements', models.PositiveIntegerField(default=10, help_text='minutes')),
                ('announcements_made', models.TextField()),
                ('host', models.CharField(max_length=20)),
                ('number_of_talent', models.PositiveIntegerField(verbose_name='Number of Student Preformances')),
                ('number_of_it_awards', models.PositiveIntegerField(default=0, verbose_name='Independent Thinker Awards')),
                ('number_of_pc_awards', models.PositiveIntegerField(default=0, verbose_name='Profiles in Courage Awards')),
                ('number_of_ds_awards', models.PositiveIntegerField(default=0, verbose_name='Durkheim Scholar Awards')),
                ('number_of_gp_awards', models.PositiveIntegerField(default=0, verbose_name='Gary Phillips Awards')),
                ('minutes_end_early', models.PositiveIntegerField(default=15, help_text='in minutes', verbose_name='Minutes Left When Community Ended')),
            ],
            options={
                'verbose_name': 'Community Instance',
                'verbose_name_plural': 'Community Instances',
            },
        ),
        migrations.CreateModel(
            name='CommunityInstanceReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.CommunityInstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),

        migrations.CreateModel(
            name='Talent',
            fields=[
                ('name', models.CharField(help_text='Use what was done, Piano, Story, Violion, Etc', max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='Describe the talent here!', null=True)),
                ('author', models.CharField(blank=True, help_text='Name the Preformer (optional)', max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='communityinstance',
            name='talent',
            field=models.ManyToManyField(blank=True, help_text="Enter all the talent that was preformed, if there was no talent preformed, don't select anything. If the talent that was preformed is not listed, use the + button to add it to the list.", to='Community.Talent'),
        ),
    ]
