# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 22:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityGameRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Community Game Rating',
                'verbose_name_plural': 'Community Game Ratings',
            },
        ),
        migrations.CreateModel(
            name='CommunityGames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Community Games',
            },
        ),
        migrations.CreateModel(
            name='CommunityInst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2017, 8, 11))),
                ('spectrum_id', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Community Instance',
                'verbose_name_plural': 'Community Instances',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='communityinstance',
            name='talent',
        ),
        migrations.RemoveField(
            model_name='communityinstancereview',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communityinstancereview',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommunityInstance',
        ),
        migrations.DeleteModel(
            name='CommunityInstanceReview',
        ),
        migrations.DeleteModel(
            name='Talent',
        ),
        migrations.AddField(
            model_name='communityinst',
            name='occuring_games',
            field=models.ManyToManyField(through='Community.CommunityGames', to='Community.Game'),
        ),
        migrations.AddField(
            model_name='communitygames',
            name='communityinst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.CommunityInst'),
        ),
        migrations.AddField(
            model_name='communitygames',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.Game'),
        ),
        migrations.AddField(
            model_name='communitygameratings',
            name='games',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.CommunityGames'),
        ),
        migrations.AddField(
            model_name='communitygameratings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
