# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 14:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0003_auto_20170811_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityinst',
            name='date',
            field=models.DateField(default=datetime.date(2017, 8, 12)),
        ),
    ]
