# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 22:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0008_auto_20170812_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityinst',
            options={'ordering': ['date'], 'verbose_name': 'Community Instance', 'verbose_name_plural': 'Community Instances'},
        ),
        migrations.AddField(
            model_name='communitygameratings',
            name='comments',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communityinst',
            name='date',
            field=models.DateField(default=datetime.date(2017, 8, 13)),
        ),
        migrations.AlterField(
            model_name='communityinst',
            name='photo',
            field=models.ImageField(default='static/Community/Community.jpg', upload_to='Community/static/Community/Community-Photos'),
        ),
    ]
