# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 18:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0010_auto_20170813_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityinst',
            name='date',
            field=models.DateField(default=datetime.date(2017, 8, 14)),
        ),
        migrations.AlterField(
            model_name='communitypacingratings',
            name='rating',
            field=models.CharField(choices=[('v', 'Very Good'), ('g', 'Good'), ('d', 'Decent'), ('b', 'Bad'), ('h', 'Very Bad')], default='d', max_length=1),
        ),
    ]
