# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0011_auto_20170814_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypacingratings',
            name='rating',
            field=models.CharField(choices=[('v', 'Very Good'), ('g', 'Good'), ('d', 'Decent'), ('b', 'Bad'), ('h', 'Very Bad')], default='d', max_length=20),
        ),
    ]
