# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0012_auto_20170814_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitygameratings',
            old_name='rating',
            new_name='game_ratings',
        ),
        migrations.RenameField(
            model_name='communitypacingratings',
            old_name='rating',
            new_name='pacing_rating',
        ),
    ]
