# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0013_auto_20170814_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitygameratings',
            old_name='game_ratings',
            new_name='game_rating',
        ),
    ]
