# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0015_auto_20170814_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityinst',
            options={'ordering': ['-date'], 'verbose_name': 'Community Instance', 'verbose_name_plural': 'Community Instances'},
        ),
    ]
