# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0016_auto_20170814_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitygameratings',
            name='like_to_see_again',
            field=models.CharField(default='n', max_length=1),
        ),
    ]
