# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 20:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0018_auto_20170814_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityinst',
            name='date',
            field=models.DateField(default=datetime.date(2017, 8, 15)),
        ),
    ]
