# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 18:00
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Community', '0019_auto_20170815_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityExtraRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.PositiveIntegerField(default=5)),
                ('extra_comments', models.TextField(blank=True, default='Describe some other thoughts that you have about community here')),
                ('how_can_we_improve_survey', models.TextField(blank=True, default="We take data collection very seriously and would love to hear student's thoughts about how it can be improved")),
            ],
        ),
        migrations.AlterField(
            model_name='communityinst',
            name='date',
            field=models.DateField(default=datetime.date(2017, 8, 16)),
        ),
        migrations.AddField(
            model_name='communityextraratings',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.CommunityInst'),
        ),
        migrations.AddField(
            model_name='communityextraratings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
