# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0023_auto_20170905_1720'),
        ('Community', '0023_auto_20170906_1821'),
    ]

    operations = [
    ]
