# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0024_merge_20170906_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitypacingratings',
            options={'verbose_name': 'Community Pacing Ratings', 'verbose_name_plural': 'Community Pacing Ratings'},
        ),
    ]
