# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 15:16
from __future__ import unicode_literals

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0025_auto_20170917_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityinst',
            name='photo',
            field=s3direct.fields.S3DirectField(),
        ),
    ]
