# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0026_auto_20170918_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityextraratings',
            name='extra_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='communityextraratings',
            name='how_can_we_improve_survey',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='communityextraratings',
            name='overall_rating',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5),
        ),
    ]
