# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0027_auto_20170921_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityextraratings',
            options={'verbose_name': 'Community Extra Ratings', 'verbose_name_plural': 'Community Extra Ratings'},
        ),
    ]
