# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0028_auto_20170921_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityextraratings',
            name='how_can_we_improve_survey',
            field=models.TextField(),
        ),
    ]
