# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 15:25
from __future__ import unicode_literals

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0029_auto_20170924_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityinst',
            name='photo',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
    ]
