# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0029_auto_20170924_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypacingratings',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communitypacingratings',
            name='user',
        ),
        migrations.AddField(
            model_name='communityextraratings',
            name='pacing_rating',
            field=models.CharField(choices=[('v', 'Very Good'), ('g', 'Good'), ('d', 'Decent'), ('b', 'Bad'), ('h', 'Very Bad')], default='d', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, default='No description'),
        ),
        migrations.DeleteModel(
            name='CommunityPacingRatings',
        ),
    ]
