# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0030_auto_20171112_1025'),
        ('Community', '0030_auto_20171105_1836'),
    ]

    operations = [
    ]
