# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Senator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='OmegaSupreme', max_length=140)),
                ('grade', models.PositiveIntegerField(choices=[(9, '9'), (10, '10'), (11, '11'), (12, '12')])),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(default='static/Senate/Senate.jpg', upload_to='Senate/static/Senate/')),
            ],
        ),
    ]
