# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-15 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Senate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='senator',
            name='position',
            field=models.CharField(choices=[('President', 'President'), ('Vice-President', 'Vice-President'), ('Secretary', 'Secretary'), ('Senator', 'Senator')], default='Senator', max_length=14),
        ),
    ]
