# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Senate', '0002_senator_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='senator',
            options={'ordering': ['-grade', 'name']},
        ),
        migrations.AlterField(
            model_name='senator',
            name='name',
            field=models.CharField(default='AlphaTrion', max_length=140),
        ),
    ]
