# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 00:09
from __future__ import unicode_literals

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Senate', '0003_auto_20170917_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senator',
            name='photo',
            field=s3direct.fields.S3DirectField(),
        ),
    ]
