# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Senate', '0005_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutes',
            name='embed_link',
            field=models.TextField(default='<iframe src="https://docs.google.com/document/d/e/2PACX-1vQdxUL4O-DG8PjqarxULpcnAB9cRwmfgxHQKLx4nqY2oc-t4UMPM21ptmyNdBGrNnxOAeom3yzqp2SN/pub?embedded=true"></iframe>', help_text='To get a embed link goto file -> publish to web -> embed -> copy the link into here'),
        ),
    ]
