# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Senate', '0006_minutes_embed_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutes',
            name='embed_link',
            field=models.TextField(default='Link Goes Here!', help_text='To get a embed link goto file -> publish to web -> embed -> copy the link into here'),
        ),
    ]
