# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 23:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Senate', '0007_auto_20171105_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minutes',
            options={'ordering': ['-date'], 'verbose_name': 'Minute', 'verbose_name_plural': 'Minutes'},
        ),
    ]
