# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 21:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0005_auto_20170924_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerInt',
            fields=[
                ('surveyanswers_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Project.SurveyAnswers')),
                ('answer', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('Project.surveyanswers',),
        ),
        migrations.CreateModel(
            name='AnswerText',
            fields=[
                ('surveyanswers_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Project.SurveyAnswers')),
                ('answer', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('Project.surveyanswers',),
        ),
    ]
