# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_answerint_answertext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerint',
            options={'verbose_name': 'Integer Answers', 'verbose_name_plural': 'Integer Answers'},
        ),
        migrations.AlterModelOptions(
            name='answertext',
            options={'verbose_name': 'Text Answers', 'verbose_name_plural': 'Text Answers'},
        ),
        migrations.AlterModelOptions(
            name='senateprojects',
            options={'verbose_name': 'Senate Project', 'verbose_name_plural': 'Senate Projects'},
        ),
        migrations.AlterModelOptions(
            name='surveyquestions',
            options={'verbose_name': 'Survey Question', 'verbose_name_plural': 'Survey Questions'},
        ),
    ]
