# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 22:08
from __future__ import unicode_literals

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_auto_20170924_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senateprojects',
            name='image',
            field=s3direct.fields.S3DirectField(null=True),
        ),
    ]
