# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 22:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0009_auto_20170924_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('date', models.DateField()),
                ('description', models.TextField(default='Insert description here')),
                ('image', s3direct.fields.S3DirectField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.CustomSurvey')),
            ],
            options={
                'verbose_name': 'Student Project',
                'verbose_name_plural': 'Student Projects',
            },
        ),
    ]
