# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='campaign_section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('url', models.CharField(choices=[('home', 'Senate Website'), ('planned-policies', 'Planned Policies'), ('personal-statement', 'Personal Statement')], max_length=200)),
                ('photo', models.ImageField(upload_to='Campaign/static/Campaign')),
            ],
        ),
    ]
